package net.swofty.type.backwaterbayou.gui;

import net.minestom.server.inventory.InventoryType;
import net.minestom.server.item.Material;
import net.swofty.type.generic.gui.inventory.ItemStackCreator;
import net.swofty.type.generic.gui.v2.DefaultState;
import net.swofty.type.generic.gui.v2.StatelessView;
import net.swofty.type.generic.gui.v2.ViewConfiguration;
import net.swofty.type.generic.gui.v2.ViewLayout;
import net.swofty.type.generic.gui.v2.context.ViewContext;

// TODO: use ShopView
public class GUIJunkerJoel extends StatelessView {

    @Override
    public ViewConfiguration<DefaultState> configuration() {
        return new ViewConfiguration<>("Junker Joel", InventoryType.CHEST_6_ROW);
    }

    @Override
    public void layout(ViewLayout<DefaultState> layout, DefaultState state, ViewContext ctx) {
        layout.slot(10, ItemStackCreator.getStackHead(
            "§9Junk Sinker",
            "d24892a3142d2e130e5feb88b805b83de905489d2ccd1d031b9d7a2922b96500",
            1,
            "§7Grants §6+10⛃ Treasure Chance §7while",
            "§7in the §2Backwater Bayou §7but replaces",
            "§7all §6Treasure §7catches with §2Junk§7!",
            "",
            "§7Talk to §2Roddy §7in the §2Backwater",
            "§2Bayou §7to apply this §9Sinker §7to a",
            "§7Fishing Rod.",
            "",
            "§9§lRARE ROD PART",
            "",
            "§7Cost",
            "§610,000 Coins",
            "",
            "§eClick to trade!"
        ));
        layout.slot(11, ItemStackCreator.getStackHead(
            "§9Treasure Bait §8x16",
            "c1695c80854447b5db5a0ee6d57ef0a7d91d815bd7e6318c516a39d12fe0639e",
            16,
            "§8Fishing Bait",
            "§8Consumes on Cast",
            "",
            "§7Grants §b+10☂ Fishing Speed§7 and §6+2⛃",
            "§6Treasure Chance§7.",
            "",
            "§9§lRARE BAIT",
            "",
            "§7Cost",
            "§aRusty Coin",
            "",
            "§eClick to trade!",
            "§eRight-click for more trading options!"
        ));
        layout.slot(12, ItemStackCreator.getStack(
            "§aChallenging Rod",
            Material.FISHING_ROD,
            1,
            "§7Damage: §c+75",
            "§7Strength: §c+75",
            "§7Fishing Speed: §b+35",
            "§7Sea Creature Chance: §3+2%",
            "",
            "§9ථ Hook §8§lNONE",
            "§9ꨃ Line §8§lNONE",
            "§9࿉ Sinker §8§lNONE",
            "",
            "§7Talk to §2Roddy §7in the §2Backwater",
            "§2Bayou §7to apply parts to this rod.",
            "",
            "§8This item can be reforged!",
            "§a§lUNCOMMON FISHING ROD",
            "",
            "§7Cost",
            "§fFishing Rod",
            "§aRusty Coin §8x16",
            "",
            "§eClick to trade!"
        ));
        layout.slot(13, ItemStackCreator.getStackHead(
            "§aBackwater Helmet",
            "f6f6c3ebab908a184d49a0f8c85edd3ed48a65d69213bc0367db67a7a1c0c3a7",
            1,
            "§7Health: §c+30",
            "§7Defense: §a+15",
            "§7Sea Creature Chance: §3+1%",
            "§7Treasure Chance: §6+0.1%",
            "",
            "§8Tiered Bonus: Swamp Soldier (0/8)",
            "§7Increases damage dealt to §3Sea",
            "§3Creatures §7by §a5%§7.",
            "",
            "§8This item can be reforged!",
            "§a§lUNCOMMON HELMET",
            "",
            "§7Cost",
            "§fAngler Helmet",
            "§aRusty Coin §8x4",
            "",
            "§eClick to trade!"
        ));
        layout.slot(14, ItemStackCreator.getStack(
            "§aBackwater Chestplate",
            Material.LEATHER_CHESTPLATE,
            1,
            "§7Health: §c+50",
            "§7Defense: §a+25",
            "§7Sea Creature Chance: §3+1%",
            "§7Treasure Chance: §6+0.1%",
            "",
            "§8Tiered Bonus: Swamp Soldier (0/8)",
            "§7Increases damage dealt to §3Sea",
            "§3Creatures §7by §a5%§7.",
            "",
            "§8This item can be reforged!",
            "§a§lUNCOMMON CHESTPLATE",
            "",
            "§7Cost",
            "§fAngler Chestplate",
            "§aRusty Coin §8x4",
            "",
            "§eClick to trade!"
        ));
        layout.slot(15, ItemStackCreator.getStack(
            "§aBackwater Leggings",
            Material.LEATHER_LEGGINGS,
            1,
            "§7Health: §c+40",
            "§7Defense: §a+20",
            "§7Sea Creature Chance: §3+1%",
            "§7Treasure Chance: §6+0.1%",
            "",
            "§8Tiered Bonus: Swamp Soldier (0/8)",
            "§7Increases damage dealt to §3Sea",
            "§3Creatures §7by §a5%§7.",
            "",
            "§8This item can be reforged!",
            "§a§lUNCOMMON LEGGINGS",
            "",
            "§7Cost",
            "§fAngler Leggings",
            "§aRusty Coin §8x4",
            "",
            "§eClick to trade!"
        ));
        layout.slot(16, ItemStackCreator.getStack(
            "§aBackwater Boots",
            Material.LEATHER_BOOTS,
            1,
            "§7Health: §c+20",
            "§7Defense: §a+10",
            "§7Sea Creature Chance: §3+1%",
            "§7Treasure Chance: §6+0.1%",
            "",
            "§8Tiered Bonus: Swamp Soldier (0/8)",
            "§7Increases damage dealt to §3Sea",
            "§3Creatures §7by §a5%§7.",
            "",
            "§8This item can be reforged!",
            "§a§lUNCOMMON BOOTS",
            "",
            "§7Cost",
            "§fAngler Boots",
            "§aRusty Coin §8x4",
            "",
            "§eClick to trade!"
        ));
        layout.slot(19, ItemStackCreator.getStackHead(
            "§fJunk Talisman",
            "d24c6d00c53b51685a6be7453d236228f9837f1c1e27a9175813983ca49c792f",
            1,
            "§7Grants §6+2.5⛃ Treasure Chance §7while",
            "§7on the §2Backwater Bayou§7.",
            "",
            "§8§oOne man's trash is another man's",
            "§8§otreasure.",
            "",
            "§8Works while in Accessory Bag!",
            "§f§lCOMMON ACCESSORY",
            "",
            "§7Cost",
            "§aRusty Coin §8x32",
            "",
            "§eClick to trade!"
        ));
        layout.slot(20, ItemStackCreator.getStackHead(
            "§aJunk Ring",
            "4c920d3593ed4936defc894b88c43a2bb0b50c3a1e9a6dd8e859cb27bd3cabd",
            1,
            "§7Grants §6+5⛃ Treasure Chance §7while",
            "§7on the §2Backwater Bayou§7.",
            "",
            "§8§oOne man's trash is another man's",
            "§8§otreasure.",
            "",
            "§8Works while in Accessory Bag!",
            "§a§lUNCOMMON ACCESSORY",
            "",
            "§7Cost",
            "§fJunk Talisman",
            "§9Busted Belt Buckle §8x4",
            "",
            "§eClick to trade!"
        ));
        layout.slot(21, ItemStackCreator.getStackHead(
            "§9Junk Artifact",
            "9727812f708dee1826bceecdadb9c7719e3d0f385a3b2515d00b5f665d8ba83e",
            1,
            "§7Grants §6+7.5⛃ Treasure Chance §7while",
            "§7on the §2Backwater Bayou§7.",
            "",
            "§8§oOne man's trash is another man's",
            "§8§otreasure.",
            "",
            "§8Works while in Accessory Bag!",
            "§9§lRARE ACCESSORY",
            "",
            "§7Cost",
            "§aJunk Ring",
            "§5Old Leather Boot",
            "",
            "§eClick to trade!"
        ));
        layout.slot(22, ItemStackCreator.getStackHead(
            "§aBackwater Necklace",
            "ab6f8eea74ca22c2ab64592bab2699df39c3e7c1db7d2c9fc687be0dc8c7f1ed",
            1,
            "§7Fishing Speed: §b+2",
            "§7Sea Creature Chance: §3+1%",
            "§7Treasure Chance: §6+0.1%",
            "",
            "§8Tiered Bonus: Swamp Soldier (0/8)",
            "§7Increases damage dealt to §3Sea",
            "§3Creatures §7by §a5%§7.",
            "",
            "§8This item can be reforged!",
            "§a§lUNCOMMON NECKLACE",
            "",
            "§7Cost",
            "§fAngler Necklace",
            "§aRusty Coin §8x4",
            "",
            "§eClick to trade!"
        ));
        layout.slot(23, ItemStackCreator.getStackHead(
            "§aBackwater Cloak",
            "f2adeecbf20b58fd4cad8aaa3b4653d7165e07aa167be48a321b096d56a9fe35",
            1,
            "§7Fishing Speed: §b+2",
            "§7Sea Creature Chance: §3+1%",
            "§7Treasure Chance: §6+0.1%",
            "",
            "§8Tiered Bonus: Swamp Soldier (0/8)",
            "§7Increases damage dealt to §3Sea",
            "§3Creatures §7by §a5%§7.",
            "",
            "§8This item can be reforged!",
            "§a§lUNCOMMON CLOAK",
            "",
            "§7Cost",
            "§fAngler Cloak",
            "§aRusty Coin §8x4",
            "",
            "§eClick to trade!"
        ));
        layout.slot(24, ItemStackCreator.getStackHead(
            "§aBackwater Belt",
            "3c150be849a39208a38a83c5605e79aef93a12b37072b931693990192cb77a19",
            1,
            "§7Fishing Speed: §b+2",
            "§7Sea Creature Chance: §3+1%",
            "§7Treasure Chance: §6+0.1%",
            "",
            "§8Tiered Bonus: Swamp Soldier (0/8)",
            "§7Increases damage dealt to §3Sea",
            "§3Creatures §7by §a5%§7.",
            "",
            "§8This item can be reforged!",
            "§a§lUNCOMMON BELT",
            "",
            "§7Cost",
            "§fAngler Belt",
            "§aRusty Coin §8x4",
            "",
            "§eClick to trade!"
        ));
        layout.slot(25, ItemStackCreator.getStackHead(
            "§aBackwater Gloves",
            "9a6c887b86b2a59fdea5052413eab74d434c07f52231ce7ac33af5b395beded0",
            1,
            "§7Fishing Speed: §b+2",
            "§7Sea Creature Chance: §3+1%",
            "§7Treasure Chance: §6+0.1%",
            "",
            "§8Tiered Bonus: Swamp Soldier (0/8)",
            "§7Increases damage dealt to §3Sea",
            "§3Creatures §7by §a5%§7.",
            "",
            "§8This item can be reforged!",
            "§a§lUNCOMMON GLOVES",
            "",
            "§7Cost",
            "§fAngler Bracelet",
            "§aRusty Coin §8x4",
            "",
            "§eClick to trade!"
        ));
        layout.slot(28, ItemStackCreator.getStackHead(
            "§7[Lvl 100] §fHermit Crab",
            "26629dfa3fdfef04054024e0156d5e19da5401b1911f59b4bd3982685fe54c2c",
            1,
            "§8Fishing Pet",
            "",
            "§7Defense: §a+20",
            "§7Fishing Speed: §b+20",
            "§7Sea Creature Chance: §3+2%",
            "",
            "§6Comfort Zone",
            "§7Grants §b+20☂ Fishing Speed §7for §a30s",
            "§7upon catching §6Treasure§7.",
            "",
            "§cThis is a preview of Lvl 100.",
            "§cNew pets are lowest level!",
            "",
            "§7Cost",
            "§aRusty Coin §8x32",
            "",
            "§eClick to trade!"
        ));
        layout.slot(29, ItemStackCreator.getStackHead(
            "§9Stingy Sinker",
            "e886d5cac32bd32fc07938908c552b7b27965d92065b3157dfc7ef849281ee9d",
            1,
            "§7Grants a §a10% §7chance to not consume",
            "§7Bait.",
            "",
            "§7Talk to §2Roddy §7in the §2Backwater",
            "§2Bayou §7to apply this §9Sinker §7to a",
            "§7Fishing Rod.",
            "",
            "§9§lRARE ROD PART",
            "",
            "§7Cost",
            "§aRusty Coin §8x64",
            "",
            "§eClick to trade!"
        ));
        layout.slot(30, ItemStackCreator.getStackHead(
            "§9Speedy Line",
            "5cbac3c84e21e65ec88007604c4eba1da391e185544b90252fc16ca695c59b4b",
            1,
            "§7Grants §b+10☂ Fishing Speed§7.",
            "",
            "§7Talk to §2Roddy §7in the §2Backwater",
            "§2Bayou §7to apply this §9Line §7to a Fishing",
            "§7Rod.",
            "",
            "§9§lRARE ROD PART",
            "",
            "§7Cost",
            "§9Busted Belt Buckle §8x8",
            "",
            "§eClick to trade!"
        ));
        layout.slot(31, ItemStackCreator.getStackHead(
            "§9Bronze Ship Engine",
            "9172c1e729e0ca00193ab5d43e893fabedf5a80fc647258176e8502432885925",
            1,
            "§8Ship Part",
            "",
            "§7Bring this item to §6Captain Baha§7.",
            "",
            "§7Grants §3+0.5☯ Fishing Wisdom §7when",
            "§7attached to your §6Ship§7.",
            "",
            "§8§l* Soulbound §l*",
            "§9§lRARE",
            "",
            "§7Cost",
            "§aRusty Coin §8x64",
            "§9Busted Belt Buckle §8x8",
            "",
            "§eClick to trade!"
        ));
        layout.slot(32, ItemStackCreator.getStackHead(
            "§6Gold Bottle Cap",
            "269698fd92fb14827af97e54a3f28f5e2685d7e94bd128c0c27f259df996717c",
            1,
            "§8Combinable in Anvil",
            "",
            "§7When applied to a fishing rod,",
            "§7increases its §9Luck of the Sea §7level",
            "§7by §a1§7!",
            "§8Can be applied once.",
            "§8Requires Luck of the Sea VI!",
            "",
            "§8§oOne man's trash is, indeed, another",
            "§8§oman's treasure.",
            "",
            "§6§lLEGENDARY",
            "",
            "§7Cost",
            "§aRusty Coin §8x512",
            "§9Busted Belt Buckle §8x64",
            "§5Old Leather Boot §8x8",
            "",
            "§eClick to trade!"
        ));
        layout.slot(33, ItemStackCreator.getStackHead(
            "§9Treasure Hook",
            "9809753cbab0380c7a1c18925faf9b51e44caadd1e5748542b0f23835f4ef64e",
            1,
            "§7Only allows you to catch items and",
            "§6Treasure§7.",
            "",
            "§7Talk to §2Roddy §7in the §2Backwater",
            "§2Bayou §7to apply this §9Hook §7to a Fishing",
            "§7Rod.",
            "",
            "§4❣ §cRequires §aFishing Skill 25§c.",
            "§9§lRARE ROD PART",
            "",
            "§7Cost",
            "§6Bayou Water Orb",
            "§5Old Leather Boot §8x4",
            "§9Busted Belt Buckle §8x32",
            "§aRusty Coin §8x256",
            "",
            "§cNot unlocked!"
        ));
        layout.slot(34, ItemStackCreator.getStack(
            "§9Travel Scroll to the Bayou",
            Material.MAP,
            1,
            "§7Consume this item to add its",
            "§7destination to your Fast Travel",
            "§7options.",
            "",
            "§7Island: §aBackwater Bayou",
            "§7Teleport: §eSpawn",
            "",
            "§9§lRARE TRAVEL SCROLL",
            "",
            "§7Cost",
            "§9Busted Belt Buckle §8x8",
            "",
            "§eClick to trade!"
        ));
        layout.slot(49, ItemStackCreator.getStack(
            "§aSell Item",
            Material.HOPPER,
            1,
            "§7Click items in your inventory to sell",
            "§7them to this Shop!"
        ));
    }
}
