package net.swofty.types.generic.collection.collections;

import net.minestom.server.item.Material;
import net.swofty.types.generic.collection.CollectionCategory;
import net.swofty.types.generic.item.ItemType;

import java.util.List;

public class MiningCollection extends CollectionCategory {
    @Override
    public Material getDisplayIcon() {
        return Material.STONE_PICKAXE;
    }

    @Override
    public String getName() {
        return "Mining";
    }

    @Override
    public ItemCollection[] getCollections() {
        return List.of(
                new ItemCollection(ItemType.COBBLESTONE,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(40000),
                        new ItemCollectionReward(70000)
                ),
                new ItemCollection(ItemType.COAL,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(50000),
                        new ItemCollectionReward(100000)
                ),
                new ItemCollection(ItemType.GOLD_INGOT,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(500),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(25000)
                ),
                new ItemCollection(ItemType.LAPIS_LAZULI,
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(500),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(50000),
                        new ItemCollectionReward(100000),
                        new ItemCollectionReward(150000),
                        new ItemCollectionReward(250000)
                ),
                new ItemCollection(ItemType.GRAVEL,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(15000),
                        new ItemCollectionReward(50000)
                ),
                new ItemCollection(ItemType.DIAMOND,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(50000)
                ),
                new ItemCollection(ItemType.EMERALD,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(15000),
                        new ItemCollectionReward(30000),
                        new ItemCollectionReward(50000),
                        new ItemCollectionReward(100000)
                ),
                new ItemCollection(ItemType.END_STONE,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(15000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(50000)
                ),
                new ItemCollection(ItemType.FINE_JASPER_GEM,
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(100000),
                        new ItemCollectionReward(250000),
                        new ItemCollectionReward(500000),
                        new ItemCollectionReward(1000000),
                        new ItemCollectionReward(2000000)
                ),
                new ItemCollection(ItemType.GLOWSTONE_DUST,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(25000)
                ),
                new ItemCollection(ItemType.HARD_STONE,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(50000),
                        new ItemCollectionReward(150000),
                        new ItemCollectionReward(300000),
                        new ItemCollectionReward(1000000)
                ),
                new ItemCollection(ItemType.ICE,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(500),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(50000),
                        new ItemCollectionReward(100000),
                        new ItemCollectionReward(250000),
                        new ItemCollectionReward(500000)
                ),
                new ItemCollection(ItemType.IRON_INGOT,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(50000),
                        new ItemCollectionReward(100000),
                        new ItemCollectionReward(200000),
                        new ItemCollectionReward(400000)
                ),
                new ItemCollection(ItemType.MITHRIL,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(250000),
                        new ItemCollectionReward(500000),
                        new ItemCollectionReward(1000000)
                ),
                new ItemCollection(ItemType.MYCELIUM,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(500),
                        new ItemCollectionReward(750),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(15000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(50000),
                        new ItemCollectionReward(100000)
                ),
                new ItemCollection(ItemType.QUARTZ,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(50000)
                ),
                new ItemCollection(ItemType.NETHERRACK,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(500),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(5000)
                ),
                new ItemCollection(ItemType.OBSIDIAN,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(50000),
                        new ItemCollectionReward(100000)
                ),
                new ItemCollection(ItemType.RED_SAND,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(500),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(15000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(50000),
                        new ItemCollectionReward(100000)
                ),
                new ItemCollection(ItemType.REDSTONE,
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(750),
                        new ItemCollectionReward(1500),
                        new ItemCollectionReward(3000),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(50000),
                        new ItemCollectionReward(200000),
                        new ItemCollectionReward(400000),
                        new ItemCollectionReward(600000),
                        new ItemCollectionReward(800000),
                        new ItemCollectionReward(1000000),
                        new ItemCollectionReward(1200000),
                        new ItemCollectionReward(1400000)
                ),
                new ItemCollection(ItemType.SAND,
                        new ItemCollectionReward(50),
                        new ItemCollectionReward(100),
                        new ItemCollectionReward(250),
                        new ItemCollectionReward(500),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000)
                ),
                new ItemCollection(ItemType.SULPHUR,
                        new ItemCollectionReward(200),
                        new ItemCollectionReward(1000),
                        new ItemCollectionReward(2500),
                        new ItemCollectionReward(5000),
                        new ItemCollectionReward(10000),
                        new ItemCollectionReward(15000),
                        new ItemCollectionReward(25000),
                        new ItemCollectionReward(50000),
                        new ItemCollectionReward(100000)
                )
        ).toArray(ItemCollection[]::new);
    }
}
