rootProject.name = "HypixelSkyBlock"
include(":packer")
include(":commons")
include(":dungeons")

include(":velocity.extension")
include(":proxy.api")

include(":service.generic")
include(":type.generic")
include(":type.skyblockgeneric")
include(":type.bedwarsgeneric")
include(":spark")
include(":loader")
include("pvp")

include(":type.prototypelobby")
include(":type.thefarmingislands")
include(":type.island")
include(":type.hub")
include(":type.dungeonhub")
include(":type.bedwarslobby")
include("type.bedwarsgame")

include(":service.auctionhouse")
include(":service.bazaar")
include(":service.itemtracker")
include(":service.api")
include(":service.datamutex")
include(":service.party")
include(":anticheat")
