package net.swofty.type.skyblockgeneric.rabbits;

import lombok.AllArgsConstructor;
import lombok.Getter;
import net.kyori.adventure.text.Component;
import net.swofty.type.skyblockgeneric.region.IslandType;

@Getter
@AllArgsConstructor
public enum ChocolateRabbit {
    AARON("Aaron", RabbitRarity.COMMON, null, null, null),
    ABLE("Able", RabbitRarity.COMMON, null, null, null),
    ACKER("Acker", RabbitRarity.COMMON, null, null, null),
    ALBUS("Albus", RabbitRarity.COMMON, null, IslandType.CRIMSON_ISLE, null),
    ALFIE("Alfie", RabbitRarity.COMMON, null, null, null),
    ALICE("Alice", RabbitRarity.COMMON, null, null, null),
    ALMOND_AMARETTO("Almond Amaretto", RabbitRarity.COMMON, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    ALPHA("Alpha", RabbitRarity.COMMON, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    ANGUS("Angus", RabbitRarity.COMMON, null, null, null),
    ANNABELLE("Annabelle", RabbitRarity.COMMON, null, null, null),
    ARCHIE("Archie", RabbitRarity.COMMON, null, null, null),
    ARNIE("Arnie", RabbitRarity.COMMON, null, null, null),
    AUDI("Audi", RabbitRarity.COMMON, null, null, null),
    AUGUSTUS("Augustus", RabbitRarity.COMMON, null, null, null),
    BABY("Baby", RabbitRarity.COMMON, null, null, null),
    BADGER("Badger", RabbitRarity.COMMON, null, null, null),
    BAGEL("Bagel", RabbitRarity.COMMON, null, null, null),
    BALDWIN("Baldwin", RabbitRarity.COMMON, null, null, null),
    BALOO("Baloo", RabbitRarity.COMMON, null, null, null),
    BARNEY("Barney", RabbitRarity.COMMON, null, null, null),
    BARTHOLOMEW("Bartholomew", RabbitRarity.COMMON, null, null, null),
    BASKET("Basket", RabbitRarity.COMMON, null, null, null),
    BAXTER("Baxter", RabbitRarity.COMMON, null, null, null),
    BAYOU("Bayou", RabbitRarity.COMMON, null, IslandType.BACKWATER_BAYOU, "Find §a15 §7unique egg locations in the §2⏣ Backwater Bayou§7."),
    BEATRICE("Beatrice", RabbitRarity.COMMON, null, null, null),
    BERTHA("Bertha", RabbitRarity.COMMON, null, null, null),
    BIBSY("Bibsy", RabbitRarity.COMMON, null, null, null),
    BILLY("Billy", RabbitRarity.COMMON, null, null, null),
    BINDI("Bindi", RabbitRarity.COMMON, null, null, null),
    BINKY("Binky", RabbitRarity.COMMON, null, null, null),
    BLAKE("Blake", RabbitRarity.COMMON, null, null, null),
    BOB("Bob", RabbitRarity.COMMON, null, null, null),
    BRAMBLE("Bramble", RabbitRarity.COMMON, null, null, null),
    BREEZE("Breeze", RabbitRarity.COMMON, null, null, null),
    BRIAN("Brian", RabbitRarity.COMMON, null, null, null),
    BRIE("Brie", RabbitRarity.COMMON, null, null, null),
    BRONSON("Bronson", RabbitRarity.COMMON, null, null, null),
    BROOKS("Brooks", RabbitRarity.COMMON, null, null, null),
    BRUCE("Bruce", RabbitRarity.COMMON, null, null, null),
    BRUNO("Bruno", RabbitRarity.COMMON, null, null, null),
    BUD("Bud", RabbitRarity.COMMON, null, null, null),
    BUGSTER("Bugster", RabbitRarity.COMMON, null, null, null),
    BUGSY("Bugsy", RabbitRarity.COMMON, null, null, null),
    BUTTERCREAM_BLOSSOM("Buttercream Blossom", RabbitRarity.COMMON, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    CADET("Cadet", RabbitRarity.COMMON, null, null, null),
    CALLIE("Callie", RabbitRarity.COMMON, null, null, null),
    CARROT("Carrot", RabbitRarity.COMMON, null, null, "Kill a §cRabbit Sprite Carrot King§7."),
    CAVE("Cave", RabbitRarity.COMMON, null, IslandType.DEEP_CAVERNS, "Find §a15 §7unique egg locations in the §b⏣ Deep Caverns§7."),
    CHASE("Chase", RabbitRarity.COMMON, null, null, null),
    CHESTER("Chester", RabbitRarity.COMMON, null, null, null),
    CHIP("Chip", RabbitRarity.COMMON, null, null, null),
    CHOMPER("Chomper", RabbitRarity.COMMON, null, null, null),
    CHOMPSKY("Chompsky", RabbitRarity.COMMON, null, null, null),
    CLAUDE("Claude", RabbitRarity.COMMON, null, null, null),
    COCOA_COMET("Cocoa Comet", RabbitRarity.COMMON, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    COLLIN("Collin", RabbitRarity.COMMON, null, null, null),
    COPPER("Copper", RabbitRarity.COMMON, null, null, null),
    COTTONTAIL("Cottontail", RabbitRarity.COMMON, null, null, null),
    CRICKET("Cricket", RabbitRarity.COMMON, null, null, null),
    CRUSH("Crush", RabbitRarity.COMMON, null, null, "Find §a100 §7duplicate rabbits."),
    CUDDLES("Cuddles", RabbitRarity.COMMON, null, null, null),
    CUPCAKE("Cupcake", RabbitRarity.COMMON, null, null, null),
    DELBOY("Delboy", RabbitRarity.COMMON, null, null, null),
    DELILAH("Delilah", RabbitRarity.COMMON, null, null, null),
    DEMI("Demi", RabbitRarity.COMMON, null, null, null),
    DIGGER("Digger", RabbitRarity.COMMON, null, null, null),
    DUCHESS("Duchess", RabbitRarity.COMMON, null, null, null),
    DULCE_DRIZZLE("Dulce Drizzle", RabbitRarity.COMMON, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    DUSTY("Dusty", RabbitRarity.COMMON, null, null, null),
    ELLIE("Ellie", RabbitRarity.COMMON, null, null, null),
    EMBER("Ember", RabbitRarity.COMMON, null, IslandType.CRIMSON_ISLE, "Find §a15 §7unique egg locations in the §c⏣ Crimson Isle§7."),
    EMERSON("Emerson", RabbitRarity.COMMON, null, null, null),
    EMMA("Emma", RabbitRarity.COMMON, null, IslandType.DEEP_CAVERNS, null),
    ESPRESSO_ECLAIR("Espresso Eclair", RabbitRarity.COMMON, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    ETA("Eta", RabbitRarity.COMMON, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    FERGIE("Fergie", RabbitRarity.COMMON, null, null, null),
    FIEVEL("Fievel", RabbitRarity.COMMON, null, null, null),
    FLUFFY("Fluffy", RabbitRarity.COMMON, null, null, null),
    FRANCINE("Francine", RabbitRarity.COMMON, null, null, null),
    FRANK("Frank", RabbitRarity.COMMON, null, null, null),
    FRANKIE("Frankie", RabbitRarity.COMMON, null, null, null),
    FUDGE("Fudge", RabbitRarity.COMMON, null, null, null),
    FUZZY("Fuzzy", RabbitRarity.COMMON, null, null, null),
    GEORGE("George", RabbitRarity.COMMON, null, null, null),
    GINGER("Ginger", RabbitRarity.COMMON, null, null, null),
    GINNY("Ginny", RabbitRarity.COMMON, null, null, null),
    GIZMO("Gizmo", RabbitRarity.COMMON, null, null, null),
    GLORIA("Gloria", RabbitRarity.COMMON, null, null, null),
    GOUDA("Gouda", RabbitRarity.COMMON, null, null, null),
    GRACIE("Gracie", RabbitRarity.COMMON, null, null, null),
    GUINNESS("Guinness", RabbitRarity.COMMON, null, null, null),
    GUNTHER("Gunther", RabbitRarity.COMMON, null, null, null),
    HADLEY("Hadley", RabbitRarity.COMMON, null, null, null),
    HARLAND("Harland", RabbitRarity.COMMON, null, IslandType.SPIDERS_DEN, null),
    HARLEY("Harley", RabbitRarity.COMMON, null, null, null),
    HEFNER("Hefner", RabbitRarity.COMMON, null, null, null),
    HEIDIE("Heidie", RabbitRarity.COMMON, null, null, null),
    HERBIE("Herbie", RabbitRarity.COMMON, null, null, null),
    HERSHEY("Hershey", RabbitRarity.COMMON, null, null, null),
    HONDO("Hondo", RabbitRarity.COMMON, null, null, null),
    HOPPER("Hopper", RabbitRarity.COMMON, null, null, null),
    HUBBY("Hubby", RabbitRarity.COMMON, null, IslandType.HUB, "Find §a15 §7unique egg locations in the §bHub§7."),
    HUCK("Huck", RabbitRarity.COMMON, null, null, null),
    HUGO("Hugo", RabbitRarity.COMMON, null, null, null),
    HUMPHREY("Humphrey", RabbitRarity.COMMON, null, null, null),
    HUNTER("Hunter", RabbitRarity.COMMON, null, null, null),
    IGGY("Iggy", RabbitRarity.COMMON, null, null, null),
    INDIE("Indie", RabbitRarity.COMMON, null, null, null),
    JACQUELINE("Jacqueline", RabbitRarity.COMMON, null, IslandType.THE_PARK, null),
    JADE("Jade", RabbitRarity.COMMON, null, IslandType.CRYSTAL_HOLLOWS, "Find §a15 §7unique egg locations in the §5⏣ Crystal Hollows§7."),
    JAKE("Jake", RabbitRarity.COMMON, null, null, null),
    JAMES("James", RabbitRarity.COMMON, null, null, null),
    JAMMER("Jammer", RabbitRarity.COMMON, null, null, null),
    JASMINE("Jasmine", RabbitRarity.COMMON, null, null, null),
    JAZMIN("Jazmin", RabbitRarity.COMMON, null, null, null),
    JEFFERY("Jeffery", RabbitRarity.COMMON, null, null, null),
    JERRY("Jerry", RabbitRarity.COMMON, null, null, "Kill a §6Villager Sprite Golden Jerry§7."),
    JOEY("Joey", RabbitRarity.COMMON, null, null, null),
    JONAH("Jonah", RabbitRarity.COMMON, null, null, null),
    JOSEPHINE("Josephine", RabbitRarity.COMMON, null, null, null),
    KRONK("Kronk", RabbitRarity.COMMON, null, IslandType.CRYSTAL_HOLLOWS, null),
    LAZY("Lazy", RabbitRarity.COMMON, null, IslandType.GOLD_MINE, null),
    LENNY("Lenny", RabbitRarity.COMMON, null, null, null),
    LILY("Lily", RabbitRarity.COMMON, null, null, null),
    LONE_RANGER("Lone Ranger", RabbitRarity.COMMON, null, null, null),
    LOTTE("Lotte", RabbitRarity.COMMON, null, null, null),
    LOUIE("Louie", RabbitRarity.COMMON, null, null, null),
    MANDY("Mandy", RabbitRarity.COMMON, null, null, null),
    MARLOW("Marlow", RabbitRarity.COMMON, null, null, null),
    MARSHALL("Marshall", RabbitRarity.COMMON, null, IslandType.GALATEA, null),
    MAUI("Maui", RabbitRarity.COMMON, null, null, null),
    MAX("Max", RabbitRarity.COMMON, null, null, null),
    MICKEY("Mickey", RabbitRarity.COMMON, null, null, null),
    MILES("Miles", RabbitRarity.COMMON, null, null, null),
    MILLY("Milly", RabbitRarity.COMMON, null, null, null),
    MIMI("Mimi", RabbitRarity.COMMON, null, IslandType.DWARVEN_MINES, "Find §a15 §7unique egg locations in the §2⏣ Dwarven Mines§7."),
    MITE("Mite", RabbitRarity.COMMON, null, IslandType.THE_END, null),
    MOCHI("Mochi", RabbitRarity.COMMON, null, null, null),
    MOLLY("Molly", RabbitRarity.COMMON, null, null, null),
    MONA("Mona", RabbitRarity.COMMON, null, null, null),
    MOODY("Moody", RabbitRarity.COMMON, null, null, null),
    MOOKIE("Mookie", RabbitRarity.COMMON, null, null, null),
    MOPSY("Mopsy", RabbitRarity.COMMON, null, null, null),
    MORRIS("Morris", RabbitRarity.COMMON, null, null, null),
    MORTY("Morty", RabbitRarity.COMMON, null, IslandType.DUNGEON_HUB, "Find §a15 §7unique egg locations in the §c⏣ Dungeon Hub§7."),
    MOTFER("Motfer", RabbitRarity.COMMON, null, IslandType.DWARVEN_MINES, null),
    NATALIE("Natalie", RabbitRarity.COMMON, null, null, null),
    NED("Ned", RabbitRarity.COMMON, null, null, null),
    NIBBLES("Nibbles", RabbitRarity.COMMON, null, null, null),
    NIKO("Niko", RabbitRarity.COMMON, null, null, null),
    NIZA("Niza", RabbitRarity.COMMON, null, null, null),
    NU("Nu", RabbitRarity.COMMON, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    NUTMEG("Nutmeg", RabbitRarity.COMMON, null, null, null),
    OLETTA("Oletta", RabbitRarity.COMMON, null, null, null),
    OLIVER("Oliver", RabbitRarity.COMMON, null, null, null),
    OLIVETTE("Olivette", RabbitRarity.COMMON, null, null, null),
    OLIVIER("Olivier", RabbitRarity.COMMON, null, null, null),
    OLLIE("Ollie", RabbitRarity.COMMON, null, null, null),
    ONION("Onion", RabbitRarity.COMMON, null, IslandType.BACKWATER_BAYOU, null),
    PADDY("Paddy", RabbitRarity.COMMON, null, null, null),
    PATCH("Patch", RabbitRarity.COMMON, null, null, null),
    PEBBLES("Pebbles", RabbitRarity.COMMON, null, null, null),
    PENNY("Penny", RabbitRarity.COMMON, null, null, null),
    PEONY("Peony", RabbitRarity.COMMON, null, null, null),
    PETUNIA("Petunia", RabbitRarity.COMMON, null, null, null),
    PICKLES("Pickles", RabbitRarity.COMMON, null, null, null),
    PICKY("Picky", RabbitRarity.COMMON, null, IslandType.GOLD_MINE, "Find §a15 §7unique egg locations in the §6⏣ Gold Mine§7."),
    PINKY("Pinky", RabbitRarity.COMMON, null, null, null),
    POPPY("Poppy", RabbitRarity.COMMON, null, null, null),
    PORTER("Porter", RabbitRarity.COMMON, null, null, null),
    POTATO("Potato", RabbitRarity.COMMON, null, IslandType.THE_FARMING_ISLANDS, null),
    QUENTIN("Quentin", RabbitRarity.COMMON, null, null, null),
    RAZZIE("Razzie", RabbitRarity.COMMON, null, null, null),
    REGINALD("Reginald", RabbitRarity.COMMON, null, null, null),
    REMI("Remi", RabbitRarity.COMMON, null, null, null),
    RESSIE("Ressie", RabbitRarity.COMMON, null, null, null),
    RICKY("Ricky", RabbitRarity.COMMON, null, null, null),
    RILEY("Riley", RabbitRarity.COMMON, null, null, null),
    ROGUE("Rogue", RabbitRarity.COMMON, null, IslandType.HUB, null),
    ROLF("Rolf", RabbitRarity.COMMON, null, null, null),
    ROSCO("Rosco", RabbitRarity.COMMON, null, null, null),
    ROSS("Ross", RabbitRarity.COMMON, null, null, null),
    ROWDY("Rowdy", RabbitRarity.COMMON, null, null, null),
    RUBEN("Ruben", RabbitRarity.COMMON, null, null, null),
    RUPERT("Rupert", RabbitRarity.COMMON, null, null, null),
    RYDER("Ryder", RabbitRarity.COMMON, null, null, null),
    SASSY("Sassy", RabbitRarity.COMMON, null, null, null),
    SCOOTER("Scooter", RabbitRarity.COMMON, null, null, null),
    SCOTCH("Scotch", RabbitRarity.COMMON, null, null, null),
    SCOUT("Scout", RabbitRarity.COMMON, null, null, null),
    SCUBA("Scuba", RabbitRarity.COMMON, null, null, null),
    SELENE("Selene", RabbitRarity.COMMON, null, null, null),
    SKIPPE("Skippe", RabbitRarity.COMMON, null, null, null),
    SMOKEY("Smokey", RabbitRarity.COMMON, null, null, null),
    SNIFFLES("Sniffles", RabbitRarity.COMMON, null, null, null),
    SNOPPY("Snoppy", RabbitRarity.COMMON, null, null, null),
    SNUFFY("Snuffy", RabbitRarity.COMMON, null, null, null),
    SOON("Soon", RabbitRarity.COMMON, null, IslandType.DUNGEON_HUB, null),
    SOPHIE("Sophie", RabbitRarity.COMMON, null, null, null),
    SORBET("Sorbet", RabbitRarity.COMMON, null, null, null),
    SPENCER("Spencer", RabbitRarity.COMMON, null, null, null),
    SPOT("Spot", RabbitRarity.COMMON, null, null, null),
    STANLEY("Stanley", RabbitRarity.COMMON, null, null, null),
    STINKY("Stinky", RabbitRarity.COMMON, null, IslandType.THE_FARMING_ISLANDS, "Find §a15 §7unique egg locations in §eThe Farming Islands§7."),
    STRIKER("Striker", RabbitRarity.COMMON, null, IslandType.SPIDERS_DEN, null),
    STUART("Stuart", RabbitRarity.COMMON, null, null, null),
    SURI("Suri", RabbitRarity.COMMON, null, null, null),
    TAGALONG("Tagalong", RabbitRarity.COMMON, null, null, null),
    TAU("Tau", RabbitRarity.COMMON, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    TEDDY("Teddy", RabbitRarity.COMMON, null, null, null),
    THALAI("Thalai", RabbitRarity.COMMON, null, null, null),
    THEO("Theo", RabbitRarity.COMMON, null, null, null),
    THEODORE("Theodore", RabbitRarity.COMMON, null, null, null),
    THUMPER("Thumper", RabbitRarity.COMMON, null, null, null),
    TICKY("Ticky", RabbitRarity.COMMON, null, null, null),
    TOBI("Tobi", RabbitRarity.COMMON, null, null, null),
    WEBB("Webb", RabbitRarity.COMMON, null, IslandType.SPIDERS_DEN, "Find §a15 §7unique egg locations in the §c⏣ Spider's Den§7."),
    WILLIAM("William", RabbitRarity.COMMON, null, null, null),
    WINSTON("Winston", RabbitRarity.COMMON, null, null, null),
    WOODY("Woody", RabbitRarity.COMMON, null, IslandType.THE_PARK, "Find §a15 §7unique egg locations in the §a⏣ The Park§7."),
    ZACK("Zack", RabbitRarity.COMMON, null, null, null),
    ZEA("Zea", RabbitRarity.COMMON, null, IslandType.THE_END, "Find §a15 §7unique egg locations in §d⏣ The End§7."),

    ABI("Abi", RabbitRarity.UNCOMMON, "Obtained through getting called by §aHoppity§7.", null, null),
    ABIGAIL("Abigail", RabbitRarity.UNCOMMON, null, null, null),
    ALEXA("Alexa", RabbitRarity.UNCOMMON, null, null, null),
    ALEXANDER("Alexander", RabbitRarity.UNCOMMON, null, null, null),
    ALPACA("Alpaca", RabbitRarity.UNCOMMON, null, null, null),
    AMAZON("Amazon", RabbitRarity.UNCOMMON, null, null, null),
    ARACHNO("Arachno", RabbitRarity.UNCOMMON, null, null, "Defeat §cTarantula Broodfather Tier III§7."),
    ASHES("Ashes", RabbitRarity.UNCOMMON, null, null, null),
    ASTERIX("Asterix", RabbitRarity.UNCOMMON, null, null, null),
    ATTILA("Attila", RabbitRarity.UNCOMMON, null, IslandType.CRIMSON_ISLE, null),
    AVERAGE("Average", RabbitRarity.UNCOMMON, null, null, "Collect §a100 §7unique §fCOMMON §7Rabbits."),
    AZURE("Azure", RabbitRarity.UNCOMMON, null, IslandType.DEEP_CAVERNS, null),
    BAMBAM("Bambam", RabbitRarity.UNCOMMON, null, null, null),
    BANDIT("Bandit", RabbitRarity.UNCOMMON, null, null, null),
    BARCODE("Barcode", RabbitRarity.UNCOMMON, null, null, null),
    BENJI("Benji", RabbitRarity.UNCOMMON, null, null, null),
    BETA("Beta", RabbitRarity.UNCOMMON, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    BILBO("Bilbo", RabbitRarity.UNCOMMON, null, null, null),
    BLOSSOM("Blossom", RabbitRarity.UNCOMMON, null, null, null),
    BLUEBERRY("Blueberry", RabbitRarity.UNCOMMON, null, null, null),
    BRICK("Brick", RabbitRarity.UNCOMMON, null, IslandType.GOLD_MINE, null),
    BRUTUS("Brutus", RabbitRarity.UNCOMMON, null, null, null),
    BUBBLES("Bubbles", RabbitRarity.UNCOMMON, null, null, null),
    BUCKWHEAT("Buckwheat", RabbitRarity.UNCOMMON, null, null, null),
    BUFFALO("Buffalo", RabbitRarity.UNCOMMON, null, null, null),
    BUGS("Bugs", RabbitRarity.UNCOMMON, null, null, null),
    BUMPER("Bumper", RabbitRarity.UNCOMMON, null, null, null),
    BUSTER("Buster", RabbitRarity.UNCOMMON, null, null, null),
    BUTTERS("Butters", RabbitRarity.UNCOMMON, null, null, null),
    CANDI("Candi", RabbitRarity.UNCOMMON, null, null, null),
    CARTER("Carter", RabbitRarity.UNCOMMON, null, null, null),
    CASPER("Casper", RabbitRarity.UNCOMMON, null, null, null),
    CASSIDY("Cassidy", RabbitRarity.UNCOMMON, null, null, null),
    CHARMIN("Charmin", RabbitRarity.UNCOMMON, null, null, null),
    CHEWY("Chewy", RabbitRarity.UNCOMMON, null, null, null),
    CHILLI("Chilli", RabbitRarity.UNCOMMON, null, null, null),
    CHUBBY("Chubby", RabbitRarity.UNCOMMON, null, null, null),
    CLOUDY("Cloudy", RabbitRarity.UNCOMMON, null, null, null),
    COOKIE("Cookie", RabbitRarity.UNCOMMON, null, null, null),
    COOPER("Cooper", RabbitRarity.UNCOMMON, null, null, null),
    COTTON("Cotton", RabbitRarity.UNCOMMON, null, null, null),
    COTTON_PUFF("Cotton Puff", RabbitRarity.UNCOMMON, null, null, null),
    COTTONBALL("Cottonball", RabbitRarity.UNCOMMON, null, null, null),
    DALTON("Dalton", RabbitRarity.UNCOMMON, null, null, null),
    DANDELION("Dandelion", RabbitRarity.UNCOMMON, null, null, null),
    DARLA("Darla", RabbitRarity.UNCOMMON, null, null, null),
    DASH("Dash", RabbitRarity.UNCOMMON, null, null, null),
    DEMARCUS("Demarcus", RabbitRarity.UNCOMMON, null, null, null),
    DEMETRIOUS("Demetrious", RabbitRarity.UNCOMMON, null, null, null),
    DESTINY("Destiny", RabbitRarity.UNCOMMON, null, null, null),
    DOMINO("Domino", RabbitRarity.UNCOMMON, null, null, null),
    DONKEY("Donkey", RabbitRarity.UNCOMMON, null, IslandType.BACKWATER_BAYOU, null),
    EASTWOOD("Eastwood", RabbitRarity.UNCOMMON, null, null, null),
    ELLA("Ella", RabbitRarity.UNCOMMON, null, null, null),
    ENDER("Ender", RabbitRarity.UNCOMMON, null, IslandType.THE_END, null),
    FIGGY("Figgy", RabbitRarity.UNCOMMON, null, IslandType.GALATEA, null),
    FITCH("Fitch", RabbitRarity.UNCOMMON, null, null, null),
    FLIP_FLOP("Flip Flop", RabbitRarity.UNCOMMON, null, null, null),
    FORREST("Forrest", RabbitRarity.UNCOMMON, null, null, null),
    FUDGE_FOUNTAIN("Fudge Fountain", RabbitRarity.UNCOMMON, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    GADGET("Gadget", RabbitRarity.UNCOMMON, null, null, null),
    GEE_GEE("Gee-Gee", RabbitRarity.UNCOMMON, null, null, null),
    GINGER_GLAZE("Ginger Glaze", RabbitRarity.UNCOMMON, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    GOOFY("Goofy", RabbitRarity.UNCOMMON, null, null, null),
    GROG("Grog", RabbitRarity.UNCOMMON, null, IslandType.CRYSTAL_HOLLOWS, null),
    HALMENROG("Halmenrog", RabbitRarity.UNCOMMON, null, IslandType.DWARVEN_MINES, null),
    HARMONY("Harmony", RabbitRarity.UNCOMMON, null, null, null),
    HONEY_HAZELNUT("Honey Hazelnut", RabbitRarity.UNCOMMON, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    HOP_A_LONG("Hop-a-long", RabbitRarity.UNCOMMON, null, null, null),
    ICING_IVY("Icing Ivy", RabbitRarity.UNCOMMON, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    INFERNO("Inferno", RabbitRarity.UNCOMMON, null, null, "Defeat §cInferno Demonlord Tier III§7."),
    IRENA("Irena", RabbitRarity.UNCOMMON, null, null, null),
    JASMINE_JELLO("Jasmine Jello", RabbitRarity.UNCOMMON, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    JAZZ("Jazz", RabbitRarity.UNCOMMON, null, null, null),
    JELLY_BEAN("Jelly Bean", RabbitRarity.UNCOMMON, null, null, null),
    KOBI("Kobi", RabbitRarity.UNCOMMON, null, null, null),
    LEOPOLD("Leopold", RabbitRarity.UNCOMMON, null, null, null),
    LULU("Lulu", RabbitRarity.UNCOMMON, null, null, null),
    MAYBELLINE("Maybelline", RabbitRarity.UNCOMMON, null, null, null),
    MEDIOCRITY("Mediocrity", RabbitRarity.UNCOMMON, null, null, "Collect §a200 §7unique §fCOMMON §7Rabbits."),
    MELON("Melon", RabbitRarity.UNCOMMON, null, IslandType.THE_FARMING_ISLANDS, null),
    MILO("Milo", RabbitRarity.UNCOMMON, null, null, null),
    MODEST("Modest", RabbitRarity.UNCOMMON, null, null, "Collect §a50 §7unique §aUNCOMMON §7Rabbits."),
    MORGAN("Morgan", RabbitRarity.UNCOMMON, null, null, null),
    OAKLEY("Oakley", RabbitRarity.UNCOMMON, null, null, null),
    OAKLY("Oakly", RabbitRarity.UNCOMMON, null, IslandType.HUB, null),
    OBELIX("Obelix", RabbitRarity.UNCOMMON, null, null, null),
    ORCHID("Orchid", RabbitRarity.UNCOMMON, null, IslandType.THE_PARK, null),
    OREO("Oreo", RabbitRarity.UNCOMMON, null, null, null),
    OTTO("Otto", RabbitRarity.UNCOMMON, null, null, null),
    OZWALD("Ozwald", RabbitRarity.UNCOMMON, null, null, null),
    PANCAKE("Pancake", RabbitRarity.UNCOMMON, null, null, null),
    PATCHES("Patches", RabbitRarity.UNCOMMON, null, null, null),
    PENELOPE("Penelope", RabbitRarity.UNCOMMON, null, null, null),
    PEPSI("Pepsi", RabbitRarity.UNCOMMON, null, null, null),
    PILLSBURY("Pillsbury", RabbitRarity.UNCOMMON, null, null, null),
    POLKA_DOT("Polka Dot", RabbitRarity.UNCOMMON, null, null, null),
    PORSCHE("Porsche", RabbitRarity.UNCOMMON, null, null, null),
    PRESTIGE("Prestige", RabbitRarity.UNCOMMON, null, null, "Reach §6Chocolate Factory III§7."),
    PRETZEL("Pretzel", RabbitRarity.UNCOMMON, null, null, null),
    PRUDENT("Prudent", RabbitRarity.UNCOMMON, null, null, "Collect §a100 §7unique §aUNCOMMON §7Rabbits."),
    QUINCY("Quincy", RabbitRarity.UNCOMMON, null, null, null),
    RAVEN("Raven", RabbitRarity.UNCOMMON, null, null, null),
    RINGO("Ringo", RabbitRarity.UNCOMMON, null, null, null),
    RUINA("Ruina", RabbitRarity.UNCOMMON, null, IslandType.DUNGEON_HUB, null),
    RUSTY("Rusty", RabbitRarity.UNCOMMON, null, null, null),
    SARGENT("Sargent", RabbitRarity.UNCOMMON, null, null, null),
    SEINFIELD("Seinfield", RabbitRarity.UNCOMMON, null, null, null),
    SNOOPY("Snoopy", RabbitRarity.UNCOMMON, null, null, null),
    SPRINKLES("Sprinkles", RabbitRarity.UNCOMMON, null, null, null),
    SQUISH("Squish", RabbitRarity.UNCOMMON, null, null, "Find §a500 §7duplicate Rabbits."),
    STEWART("Stewart", RabbitRarity.UNCOMMON, null, null, null),
    SVEN("Sven", RabbitRarity.UNCOMMON, null, null, "Defeat §9Sven Packmaster Tier III§7."),
    SWEETPEA("Sweetpea", RabbitRarity.UNCOMMON, null, null, null),
    SYLVESTER("Sylvester", RabbitRarity.UNCOMMON, null, null, null),
    THETA("Theta", RabbitRarity.UNCOMMON, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    TOBY("Toby", RabbitRarity.UNCOMMON, null, null, null),
    TRIXIE("Trixie", RabbitRarity.UNCOMMON, null, null, null),
    UNA("Una", RabbitRarity.UNCOMMON, null, null, null),
    UPSILON("Upsilon", RabbitRarity.UNCOMMON, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    VOID("Void", RabbitRarity.UNCOMMON, null, null, "Defeat §5Voidgloom Seraph Tier III§7."),
    WADSWORTH("Wadsworth", RabbitRarity.UNCOMMON, null, null, null),
    WAFFLE("Waffle", RabbitRarity.UNCOMMON, null, null, null),
    XI("Xi", RabbitRarity.UNCOMMON, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    ZOMBIE("Zombie", RabbitRarity.UNCOMMON, null, null, "Defeat §5Revenant Horror Tier III§7."),

    ALADDIN("Aladdin", RabbitRarity.RARE, null, null, null),
    ALOYSIUS("Aloysius", RabbitRarity.RARE, null, null, null),
    BARBIE("Barbie", RabbitRarity.RARE, null, null, null),
    BISHOP("Bishop", RabbitRarity.RARE, null, null, null),
    BLACKBERRY("Blackberry", RabbitRarity.RARE, null, null, null),
    BLACKJACK("Blackjack", RabbitRarity.RARE, null, null, null),
    BOULDER("Boulder", RabbitRarity.RARE, null, IslandType.GOLD_MINE, null),
    BUGATTI("Bugatti", RabbitRarity.RARE, null, null, null),
    BUN_BUN("Bun Bun", RabbitRarity.RARE, null, null, null),
    BURST("Burst", RabbitRarity.RARE, null, null, "Find §a1,000 §7duplicate Rabbits."),
    CAJUN("Cajun", RabbitRarity.RARE, null, null, null),
    CANOPUS("Canopus", RabbitRarity.RARE, null, IslandType.THE_PARK, null),
    CARAMEL("Caramel", RabbitRarity.RARE, null, null, null),
    CARMINE("Carmine", RabbitRarity.RARE, null, IslandType.DEEP_CAVERNS, null),
    CASANOVA("Casanova", RabbitRarity.RARE, null, null, null),
    CHEVY("Chevy", RabbitRarity.RARE, null, null, null),
    CINNAMON("Cinnamon", RabbitRarity.RARE, null, null, null),
    COLTRON("Coltron", RabbitRarity.RARE, null, IslandType.CRYSTAL_HOLLOWS, null),
    CRYSTAL("Crystal", RabbitRarity.RARE, null, null, null),
    DALLAS("Dallas", RabbitRarity.RARE, null, null, null),
    DRACO("Draco", RabbitRarity.RARE, null, null, null),
    EASTER("Easter", RabbitRarity.RARE, null, null, null),
    EGG("Egg", RabbitRarity.RARE, null, IslandType.THE_END, null),
    ELVIS("Elvis", RabbitRarity.RARE, null, null, null),
    FAVOR("Favor", RabbitRarity.RARE, null, null, "Collect §a50 §7unique §9RARE §7Rabbits."),
    FIGARO("Figaro", RabbitRarity.RARE, null, null, null),
    FISH_THE_RABBIT("Fish the Rabbit", RabbitRarity.RARE, "Obtained by finding the §6Stray Rabbit §7in the Chocolate Factory menu.", null, null),
    FRODO("Frodo", RabbitRarity.RARE, null, null, null),
    GAMMA("Gamma", RabbitRarity.RARE, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    GRAVLER("Gravler", RabbitRarity.RARE, null, IslandType.SPIDERS_DEN, null),
    GREMLIN("Gremlin", RabbitRarity.RARE, null, null, null),
    HONEY("Honey", RabbitRarity.RARE, null, null, null),
    HOPE("Hope", RabbitRarity.RARE, null, null, null),
    HYDE("Hyde", RabbitRarity.RARE, null, null, null),
    IOTA("Iota", RabbitRarity.RARE, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    JASPER("Jasper", RabbitRarity.RARE, null, null, null),
    JYNX("Jynx", RabbitRarity.RARE, null, null, null),
    KALUMDAI("Kalumdai", RabbitRarity.RARE, null, IslandType.DWARVEN_MINES, null),
    KIWI_KISS("Kiwi Kiss", RabbitRarity.RARE, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    LAVENDER_LEMON("Lavender Lemon", RabbitRarity.RARE, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    LINUS("Linus", RabbitRarity.RARE, null, null, null),
    LUMIE("Lumie", RabbitRarity.RARE, null, IslandType.GALATEA, null),
    MAPLE_MIRAGE("Maple Mirage", RabbitRarity.RARE, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    MIDNIGHT("Midnight", RabbitRarity.RARE, null, null, null),
    MONALISA("Monalisa", RabbitRarity.RARE, null, null, null),
    MURPHY("Murphy", RabbitRarity.RARE, null, null, null),
    MUSH_MUSH("Mush Mush", RabbitRarity.RARE, null, IslandType.DUNGEON_HUB, null),
    MUTONIO("Mutonio", RabbitRarity.RARE, null, IslandType.THE_FARMING_ISLANDS, null),
    NEPTUNE("Neptune", RabbitRarity.RARE, null, null, null),
    NOUGAT_NEBULA("Nougat Nebula", RabbitRarity.RARE, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    OLYMPE("Olympe", RabbitRarity.RARE, null, null, null),
    OMICRON("Omicron", RabbitRarity.RARE, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    ONYX("Onyx", RabbitRarity.RARE, null, null, null),
    ORANGE_OBSIDIAN("Orange Obsidian", RabbitRarity.RARE, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    ORLANDO("Orlando", RabbitRarity.RARE, null, null, null),
    PADDINGTON("Paddington", RabbitRarity.RARE, null, null, null),
    PEANUT("Peanut", RabbitRarity.RARE, null, null, null),
    PEPPER("Pepper", RabbitRarity.RARE, null, null, null),
    PHANTOM("Phantom", RabbitRarity.RARE, null, null, null),
    PHI("Phi", RabbitRarity.RARE, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    POPCORN("Popcorn", RabbitRarity.RARE, null, null, null),
    PRIDE("Pride", RabbitRarity.RARE, null, null, null),
    PUMPKIN("Pumpkin", RabbitRarity.RARE, null, null, null),
    RIVER("River", RabbitRarity.RARE, null, null, null),
    SAGE("Sage", RabbitRarity.RARE, null, null, null),
    SHERK("Sherk", RabbitRarity.RARE, null, IslandType.BACKWATER_BAYOU, null),
    SNOWBALL("Snowball", RabbitRarity.RARE, null, null, null),
    SPIRIT("Spirit", RabbitRarity.RARE, null, null, null),
    SPOOKY("Spooky", RabbitRarity.RARE, null, null, null),
    STORMY("Stormy", RabbitRarity.RARE, null, null, null),
    SULFUR("Sulfur", RabbitRarity.RARE, null, IslandType.CRIMSON_ISLE, null),
    SUNNY("Sunny", RabbitRarity.RARE, null, null, null),
    TORNADO("Tornado", RabbitRarity.RARE, null, null, null),
    TOWNY("Towny", RabbitRarity.RARE, null, IslandType.HUB, null),
    TRICKY("Tricky", RabbitRarity.RARE, null, null, null),
    UNCLE_BUCK("Uncle Buck", RabbitRarity.RARE, null, null, null),
    VLAD("Vlad", RabbitRarity.RARE, null, null, null),
    WESSON("Wesson", RabbitRarity.RARE, null, null, null),
    WIDGET("Widget", RabbitRarity.RARE, null, null, null),
    WILLOW("Willow", RabbitRarity.RARE, null, null, null),
    ZERO("Zero", RabbitRarity.RARE, null, null, null),

    ACE("Ace", RabbitRarity.EPIC, null, null, null),
    ACHILLES("Achilles", RabbitRarity.EPIC, null, null, null),
    ALPINE("Alpine", RabbitRarity.EPIC, null, null, null),
    ANGEL("Angel", RabbitRarity.EPIC, null, null, null),
    CALYPSO("Calypso", RabbitRarity.EPIC, null, null, null),
    CASTLE("Castle", RabbitRarity.EPIC, null, IslandType.HUB, null),
    CHI("Chi", RabbitRarity.EPIC, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    COMET("Comet", RabbitRarity.EPIC, null, null, null),
    DELTA("Delta", RabbitRarity.EPIC, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    DOJO("Dojo", RabbitRarity.EPIC, null, IslandType.CRIMSON_ISLE, null),
    EISEN("Eisen", RabbitRarity.EPIC, null, IslandType.CRIMSON_ISLE, null),
    GATSBY("Gatsby", RabbitRarity.EPIC, null, null, null),
    GROVE("Grove", RabbitRarity.EPIC, null, IslandType.GALATEA, null),
    HOLE("Hole", RabbitRarity.EPIC, null, IslandType.GOLD_MINE, null),
    IMPLODE("Implode", RabbitRarity.EPIC, null, null, "Find §a2,000 §7duplicate Rabbits."),
    JEDI("Jedi", RabbitRarity.EPIC, null, null, null),
    KAPPA("Kappa", RabbitRarity.EPIC, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    KEN("Ken", RabbitRarity.EPIC, null, null, null),
    KIERA("Kiera", RabbitRarity.EPIC, null, null, null),
    KODO("Kodo", RabbitRarity.EPIC, null, null, null),
    KRYS("Krys", RabbitRarity.EPIC, null, IslandType.DUNGEON_HUB, null),
    MAXIMA("Maxima", RabbitRarity.EPIC, null, IslandType.SPIDERS_DEN, null),
    MERLIN("Merlin", RabbitRarity.EPIC, null, null, null),
    NEARQUAAD("Nearquaad", RabbitRarity.EPIC, null, IslandType.BACKWATER_BAYOU, null),
    NECRON("Necron", RabbitRarity.EPIC, null, null, "§cThe Catacombs Floor VII §7Completion"),
    OCTAVIA("Octavia", RabbitRarity.EPIC, null, IslandType.DWARVEN_MINES, null),
    PEARL("Pearl", RabbitRarity.EPIC, null, IslandType.THE_END, null),
    PEPPERMINT_PEARL("Peppermint Pearl", RabbitRarity.EPIC, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    PI("Pi", RabbitRarity.EPIC, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    PRINCE("Prince", RabbitRarity.EPIC, null, null, null),
    PUNCH("Punch", RabbitRarity.EPIC, null, null, null),
    QUINCE_QUARK("Quince Quark", RabbitRarity.EPIC, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    RAMBO("Rambo", RabbitRarity.EPIC, null, null, null),
    RASPBERRY_RIPPLE("Raspberry Ripple", RabbitRarity.EPIC, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    ROCHIE("Rochie", RabbitRarity.EPIC, null, IslandType.THE_FARMING_ISLANDS, null),
    SAGA("Saga", RabbitRarity.EPIC, null, null, "Collect §a25 §7unique §5EPIC §7Rabbits."),
    SAVANNAH("Savannah", RabbitRarity.EPIC, null, IslandType.THE_PARK, null),
    SIMBA("Simba", RabbitRarity.EPIC, null, null, null),
    STRAWBERRY_SWIRL("Strawberry Swirl", RabbitRarity.EPIC, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    THOR("Thor", RabbitRarity.EPIC, null, null, null),
    TOFFEE_TULIP("Toffee Tulip", RabbitRarity.EPIC, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    TRIX("Trix", RabbitRarity.EPIC, null, null, null),
    TURBO("Turbo", RabbitRarity.EPIC, null, null, null),
    VIOLET("Violet", RabbitRarity.EPIC, null, IslandType.CRYSTAL_HOLLOWS, null),

    APOLLO("Apollo", RabbitRarity.LEGENDARY, null, null, null),
    APRIL("April", RabbitRarity.LEGENDARY, null, null, null),
    ATLAS("Atlas", RabbitRarity.LEGENDARY, null, null, null),
    ECHO("Echo", RabbitRarity.LEGENDARY, null, null, null),
    EL_DORADO("El Dorado", RabbitRarity.LEGENDARY, "Obtained by finding the §6Stray Rabbit §7in the Chocolate Factory menu.", null, null),
    EPSILON("Epsilon", RabbitRarity.LEGENDARY, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    EXTRA("Extra", RabbitRarity.LEGENDARY, null, null, "Collect §a20 §7unique §6LEGENDARY §7Rabbits."),
    GENERAL("General", RabbitRarity.LEGENDARY, null, null, null),
    HOUDINI("Houdini", RabbitRarity.LEGENDARY, null, null, null),
    KAEMAN("Kaeman", RabbitRarity.LEGENDARY, null, null, "§cMaster Mode The Catacombs Floor VII §7Completion"),
    LAMBDA("Lambda", RabbitRarity.LEGENDARY, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    MAGIC("Magic", RabbitRarity.LEGENDARY, null, null, null),
    MYSTIC("Mystic", RabbitRarity.LEGENDARY, null, null, null),
    NOVA("Nova", RabbitRarity.LEGENDARY, null, null, null),
    PSI("Psi", RabbitRarity.LEGENDARY, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    RHO("Rho", RabbitRarity.LEGENDARY, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    SHADOW("Shadow", RabbitRarity.LEGENDARY, null, null, null),
    SOLOMON("Solomon", RabbitRarity.LEGENDARY, null, null, null),
    STORM("Storm", RabbitRarity.LEGENDARY, null, null, null),
    UBE_UNICORN("Ube Unicorn", RabbitRarity.LEGENDARY, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    VANILLA_VORTEX("Vanilla Vortex", RabbitRarity.LEGENDARY, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    WALNUT_WHIRL("Walnut Whirl", RabbitRarity.LEGENDARY, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    XOCO_XANUDU("Xoco Xanudu", RabbitRarity.LEGENDARY, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    YOGURT_YUCCA("Yogurt Yucca", RabbitRarity.LEGENDARY, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),

    DANTE("Dante", RabbitRarity.MYTHIC, null, null, null),
    EINSTEIN("Einstein", RabbitRarity.MYTHIC, null, null, null),
    GALAXY("Galaxy", RabbitRarity.MYTHIC, null, null, null),
    KING("King", RabbitRarity.MYTHIC, null, null, null),
    MU("Mu", RabbitRarity.MYTHIC, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    NAPOLEON("Napoleon", RabbitRarity.MYTHIC, null, null, null),
    OMEGA("Omega", RabbitRarity.MYTHIC, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    SIGMA("Sigma", RabbitRarity.MYTHIC, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    ZEST_ZEPHYR("Zest Zephyr", RabbitRarity.MYTHIC, "Obtained through your §6Chocolate Factory Milestones§7.", null, null),
    ZETA("Zeta", RabbitRarity.MYTHIC, "Obtained through your §6Chocolate Shop Milestones§7.", null, null),
    ZORRO("Zorro", RabbitRarity.MYTHIC, null, null, null),

    AURORA("Aurora", RabbitRarity.DIVINE, null, null, null),
    CELESTIA("Celestia", RabbitRarity.DIVINE, null, null, null),
    ORION("Orion", RabbitRarity.DIVINE, null, null, null),
    STARFIRE("Starfire", RabbitRarity.DIVINE, null, null, null),
    VEGA("Vega", RabbitRarity.DIVINE, null, null, null);

    private final String displayName;
    private final RabbitRarity rarity;
    private final String obtainMethod;
    private final IslandType location;
    private final String requirement; // TODO: move to components

    public int getChocolateBonus() {
        return rarity.getChocolateBonus();
    }

    public double getMultiplierBonus() {
        return rarity.getMultiplierBonus();
    }

    public String getFormattedName() {
        return "§" + rarity.getColorCode() + displayName;
    }

    public Component getFormattedLocation() {
        return location == null ? null : location.getFormattedName();
    }

    public Component getResidentLabel() {
        return location == null ? null : location.getResidentLabel();
    }

    public static int getTotalRabbits() {
        return values().length;
    }

    public static int getRabbitCountByRarity(RabbitRarity rarity) {
        int count = 0;
        for (ChocolateRabbit rabbit : values()) {
            if (rabbit.rarity == rarity) {
                count++;
            }
        }
        return count;
    }

    @Getter
    @AllArgsConstructor
    public enum RabbitRarity {
        COMMON("f", "COMMON", 1, 0.002),
        UNCOMMON("a", "UNCOMMON", 2, 0.003),
        RARE("9", "RARE", 4, 0.004),
        EPIC("5", "EPIC", 10, 0.005),
        LEGENDARY("6", "LEGENDARY", 0, 0.02),
        MYTHIC("d", "MYTHIC", 0, 0.05),
        DIVINE("b", "DIVINE", 0, 0.03);

        private final String colorCode;
        private final String displayName;
        private final int chocolateBonus;
        private final double multiplierBonus;

        public String getFormattedName() {
            return "§" + colorCode + "§l" + displayName + " RABBIT";
        }
    }
}