apiVersion: v1
kind: ConfigMap
metadata:
  name: hypixel-config
  namespace: hypixel
data:
  HYPIXEL_HOST_NAME: "0.0.0.0"
  HYPIXEL_ADVERTISED_PORT: "25565"
  HYPIXEL_MANAGEMENT_ENABLED: "true"
  HYPIXEL_MANAGEMENT_HOST_NAME: "0.0.0.0"
  HYPIXEL_MANAGEMENT_PORT: "9090"
