apiVersion: v1
kind: Secret
metadata:
  name: hypixel-secrets
  namespace: hypixel
type: Opaque
stringData:
  HYPIXEL_MONGODB: "mongodb://mongodb.hypixel.svc.cluster.local:27017"
  HYPIXEL_REDIS_URI: "redis://redis.hypixel.svc.cluster.local:6379"
  HYPIXEL_VELOCITY_SECRET: "replace-me"
  FORWARDING_SECRET: "replace-me"
