FROM eclipse-temurin:25-jdk

WORKDIR /app

RUN apt-get update && apt-get install -y jq curl && apt-get clean

# Download all JARs in a single layer
RUN curl -fSL -o HypixelCore.jar "https://github.com/Swofty-Developments/HypixelSkyBlock/releases/download/latest/HypixelCore.jar" && \
    curl -fSL -o ServiceAPI.jar "https://github.com/Swofty-Developments/HypixelSkyBlock/releases/download/latest/ServiceAPI.jar" && \
    curl -fSL -o ServiceAuctionHouse.jar "https://github.com/Swofty-Developments/HypixelSkyBlock/releases/download/latest/ServiceAuctionHouse.jar" && \
    curl -fSL -o ServiceBazaar.jar "https://github.com/Swofty-Developments/HypixelSkyBlock/releases/download/latest/ServiceBazaar.jar" && \
    curl -fSL -o ServiceItemTracker.jar "https://github.com/Swofty-Developments/HypixelSkyBlock/releases/download/latest/ServiceItemTracker.jar" && \
    curl -fSL -o ServiceDataMutex.jar "https://github.com/Swofty-Developments/HypixelSkyBlock/releases/download/latest/ServiceDataMutex.jar" && \
    curl -fSL -o ServiceParty.jar "https://github.com/Swofty-Developments/HypixelSkyBlock/releases/download/latest/ServiceParty.jar" && \
    curl -fSL -o ServiceDarkAuction.jar "https://github.com/Swofty-Developments/HypixelSkyBlock/releases/download/latest/ServiceDarkAuction.jar" && \
    curl -fSL -o ServiceOrchestrator.jar "https://github.com/Swofty-Developments/HypixelSkyBlock/releases/download/latest/ServiceOrchestrator.jar" && \
    curl -fSL -o ServiceFriend.jar "https://github.com/Swofty-Developments/HypixelSkyBlock/releases/download/latest/ServiceFriend.jar"

# Copy configuration data
COPY ./configuration /app/configuration_files

RUN mkdir -p configuration && \
    cp configuration_files/config.yml ./configuration/config.yml

RUN curl -fSL -o /tmp/worlds.tar.gz "https://files.catbox.moe/9uas8z.gz" && \
    tar -xzf /tmp/worlds.tar.gz -C ./configuration && \
    rm /tmp/worlds.tar.gz

EXPOSE 25565 65535 8080 20000

RUN cp configuration_files/NanoLimbo-1.10.2.jar ./NanoLimbo-1.10.2.jar && \
    cp configuration_files/settings.yml ./settings.yml && \
    cp -a configuration_files/skyblock/. configuration/skyblock/ && \
    cp configuration_files/entrypoint.sh ./entrypoint.sh && \
    chmod +x entrypoint.sh && \
    sed -i "s/ip: 'localhost'/ip: '0.0.0.0'/" ./settings.yml

CMD ["sh", "entrypoint.sh"]
