package net.swofty.type.skyblockgeneric.item;

import lombok.Getter;
import net.swofty.commons.skyblock.item.ItemType;

@Getter
public enum TieredTalismansRegistry {
    SCARF(true, ItemType.SCARFS_STUDIES, ItemType.SCARFS_THESIS, ItemType.SCARFS_GRIMOIRE),
    SPEED(true, ItemType.SPEED_TALISMAN, ItemType.SPEED_RING, ItemType.SPEED_ARTIFACT),
    SPIDER(true, ItemType.SPIDER_TALISMAN, ItemType.SPIDER_RING, ItemType.SPIDER_ARTIFACT),
    WOLF(true, ItemType.WOLF_TALISMAN, ItemType.WOLF_RING),
    HEALING(true, ItemType.HEALING_TALISMAN, ItemType.HEALING_RING),
    SCAVENGER(true, ItemType.SCAVENGER_TALISMAN, ItemType.SCAVENGER_RING, ItemType.SCAVENGER_ARTIFACT),
    TREASURE(true, ItemType.TREASURE_TALISMAN, ItemType.TREASURE_RING, ItemType.TREASURE_ARTIFACT),
    ZOMBIE(true, ItemType.ZOMBIE_TALISMAN, ItemType.ZOMBIE_RING, ItemType.ZOMBIE_ARTIFACT),
    FISH_BOWL(true, ItemType.SMALL_FISH_BOWL, ItemType.MEDIUM_FISH_BOWL, ItemType.LARGE_FISH_BOWL),
    RUNEBLADE(true, ItemType.RUNEBLADE_TALISMAN, ItemType.RUNEBLADE_RING, ItemType.RUNEBLADE_ARTIFACT),
    EMERALD(true, ItemType.EMERALD_RING, ItemType.EMERALD_ARTIFACT),
    WITHER(true, ItemType.WITHER_ARTIFACT, ItemType.WITHER_RELIC),
    HASTE(true, ItemType.HASTE_RING, ItemType.HASTE_ARTIFACT),
    PRESSURE(true, ItemType.PRESSURE_TALISMAN, ItemType.PRESSURE_RING, ItemType.PRESSURE_ARTIFACT),
    EMPEROR(true, ItemType.EMPEROR_TALISMAN, ItemType.EMPEROR_RING, ItemType.EMPEROR_ARTIFACT),
    MOONGLADE(true, ItemType.MOONGLADE_TALISMAN, ItemType.MOONGLADE_RING, ItemType.MOONGLADE_ARTIFACT),
    RESPIRATION(true, ItemType.RESPIRATION_TALISMAN, ItemType.RESPIRATION_RING, ItemType.RESPIRATION_ARTIFACT),
    DRACONIC(true, ItemType.DRACONIC_TALISMAN, ItemType.DRACONIC_RING, ItemType.DRACONIC_ARTIFACT),
    BLOOD_DONOR(true, ItemType.BLOOD_DONOR_TALISMAN, ItemType.BLOOD_DONOR_RING, ItemType.BLOOD_DONOR_ARTIFACT),
    AGARIMOO(true, ItemType.AGARIMOO_TALISMAN, ItemType.AGARIMOO_RING, ItemType.AGARIMOO_ARTIFACT),
    LUSH(true, ItemType.LUSH_TALISMAN, ItemType.LUSH_RING, ItemType.LUSH_ARTIFACT),
    GLACIAL(true, ItemType.GLACIAL_TALISMAN, ItemType.GLACIAL_RING, ItemType.GLACIAL_ARTIFACT),
    GIFT(true, ItemType.WHITE_GIFT_TALISMAN, ItemType.GREEN_GIFT_TALISMAN, ItemType.BLUE_GIFT_TALISMAN, ItemType.PURPLE_GIFT_TALISMAN, ItemType.GOLD_GIFT_TALISMAN),
    TITANIUM(true, ItemType.TITANIUM_TALISMAN, ItemType.TITANIUM_RING, ItemType.TITANIUM_ARTIFACT, ItemType.TITANIUM_RELIC),
    PIGGY(false, ItemType.PIGGY_BANK, ItemType.CRACKED_PIGGY_BANK, ItemType.BROKEN_PIGGY_BANK),
    ODGER(true, ItemType.ODGERS_BRONZE_TOOTH, ItemType.ODGERS_SILVER_TOOTH, ItemType.ODGERS_GOLD_TOOTH, ItemType.ODGERS_DIAMOND_TOOTH),
    SEAL(true, ItemType.SEAL_TALISMAN, ItemType.SEAL_RING),
    BINGO(true, ItemType.BINGO_TALISMAN, ItemType.BINGO_RING, ItemType.BINGO_ARTIFACT, ItemType.BINGO_RELIC),
    SHARK(true, ItemType.RAGGEDY_SHARK_TOOTH_NECKLACE, ItemType.DULL_SHARK_TOOTH_NECKLACE, ItemType.HONED_SHARK_TOOTH_NECKLACE, ItemType.SHARP_SHARK_TOOTH_NECKLACE, ItemType.RAZOR_SHARP_SHARK_TOOTH_NECKLACE),
    JERRY(true, ItemType.JERRY_TALISMAN_GREEN, ItemType.JERRY_TALISMAN_BLUE, ItemType.JERRY_TALISMAN_PURPLE, ItemType.JERRY_TALISMAN_GOLDEN),
    PESTHUNTER(true, ItemType.PESTHUNTER_BADGE, ItemType.PESTHUNTER_RING, ItemType.PESTHUNTER_ARTIFACT, ItemType.PESTHUNTER_RELIC),
    ANGUISH(true, ItemType.ANGUISH_TALISMAN, ItemType.ANGUISH_RING, ItemType.ANGUISH_ARTIFACT),
    BEASTMASTER(true, ItemType.BEASTMASTER_CREST_COMMON, ItemType.BEASTMASTER_CREST_UNCOMMON, ItemType.BEASTMASTER_CREST_RARE, ItemType.BEASTMASTER_CREST_EPIC, ItemType.BEASTMASTER_CREST_LEGENDARY),
    MINERAL(true, ItemType.MINERAL_TALISMAN, ItemType.GLOSSY_MINERAL_TALISMAN),
    GREATSPOOK(true, ItemType.GREAT_SPOOK_TALISMAN, ItemType.GREAT_SPOOK_RING, ItemType.GREAT_SPOOK_ARTIFACT),
    CHOCOLATE(true, ItemType.NIBBLE_CHOCOLATE_STICK, ItemType.SMOOTH_CHOCOLATE_BAR, ItemType.RICH_CHOCOLATE_CHUNK, ItemType.GANACHE_CHOCOLATE_SLAB, ItemType.PRESTIGE_CHOCOLATE_REALM),
    CENTURY(true, ItemType.CENTURY_TALISMAN, ItemType.CENTURY_RING),
    JUNK(true, ItemType.JUNK_TALISMAN, ItemType.JUNK_RING, ItemType.JUNK_ARTIFACT),
    FROZEN_CHICKEN(true, ItemType.FROZEN_CHICKEN, ItemType.FRIED_FROZEN_CHICKEN),
    ANITA(true, ItemType.ANITA_TALISMAN, ItemType.ANITA_RING, ItemType.ANITA_ARTIFACT),
    GARDEN(true, ItemType.CROPIE_TALISMAN, ItemType.SQUASH_RING, ItemType.FERMENTO_ARTIFACT, ItemType.HELIANTHUS_RELIC),
    BIOANALYSIS(true, ItemType.BIOANALYSIS_TALISMAN, ItemType.BIOANALYSIS_RING, ItemType.BIOANALYSIS_ARTIFACT),
    POWER(true, ItemType.POWER_TALISMAN, ItemType.POWER_RING, ItemType.POWER_ARTIFACT, ItemType.POWER_RELIC),
    RED_CLAW(true, ItemType.RED_CLAW_TALISMAN, ItemType.RED_CLAW_RING, ItemType.RED_CLAW_ARTIFACT),
    HUNTER(true, ItemType.HUNTER_TALISMAN, ItemType.HUNTER_RING),
    SOULFLOW(true, ItemType.SOULFLOW_PILE, ItemType.SOULFLOW_BATTERY, ItemType.SOULFLOW_SUPERCELL),
    ENDER(true, ItemType.ENDER_ARTIFACT, ItemType.ENDER_RELIC),
    BURSTSTOPPER(true, ItemType.BURSTSTOPPER_TALISMAN, ItemType.BURSTSTOPPER_ARTIFACT),
    KUUDRA_CORE(true, ItemType.BURNING_KUUDRA_CORE, ItemType.FIERY_KUUDRA_CORE, ItemType.INFERNAL_KUUDRA_CORE),
    POTION(true, ItemType.POTION_AFFINITY_TALISMAN, ItemType.RING_POTION_AFFINITY, ItemType.ARTIFACT_POTION_AFFINITY),
    SEA_CREATURE(true, ItemType.SEA_CREATURE_TALISMAN, ItemType.SEA_CREATURE_RING, ItemType.SEA_CREATURE_ARTIFACT),
    VACCINE(true, ItemType.VACCINE_TALISMAN, ItemType.VACCINE_RING, ItemType.VACCINE_ARTIFACT),
    BAT_PERSON(true, ItemType.BAT_PERSON_TALISMAN, ItemType.BAT_PERSON_RING, ItemType.BAT_PERSON_ARTIFACT),
    CANDY(true, ItemType.CANDY_TALISMAN, ItemType.CANDY_RING, ItemType.CANDY_ARTIFACT),
    CAT(true, ItemType.CAT_TALISMAN, ItemType.LYNX_TALISMAN, ItemType.CHEETAH_TALISMAN),
    BAT(true, ItemType.BAT_TALISMAN, ItemType.BAT_RING, ItemType.BAT_ARTIFACT),
    FEATHER(true, ItemType.FEATHER_TALISMAN, ItemType.FEATHER_RING, ItemType.FEATHER_ARTIFACT),
    PERSONAL_COMPACTOR(true, ItemType.PERSONAL_COMPACTOR_4000, ItemType.PERSONAL_COMPACTOR_5000, ItemType.PERSONAL_COMPACTOR_6000, ItemType.PERSONAL_COMPACTOR_7000),
    PERSONAL_DELETOR(true, ItemType.PERSONAL_DELETOR_4000, ItemType.PERSONAL_DELETOR_5000, ItemType.PERSONAL_DELETOR_6000, ItemType.PERSONAL_DELETOR_7000),
    INTIMIDATION(true, ItemType.INTIMIDATION_TALISMAN, ItemType.INTIMIDATION_RING, ItemType.INTIMIDATION_ARTIFACT, ItemType.INTIMIDATION_RELIC),
    COIN(true, ItemType.COIN_TALISMAN, ItemType.RING_OF_COINS, ItemType.ARTIFACT_OF_COINS, ItemType.RELIC_OF_COINS),
    MASTER_SKULL(true, ItemType.MASTER_SKULL_TIER_1, ItemType.MASTER_SKULL_TIER_2, ItemType.MASTER_SKULL_TIER_3, ItemType.MASTER_SKULL_TIER_4, ItemType.MASTER_SKULL_TIER_5, ItemType.MASTER_SKULL_TIER_6, ItemType.MASTER_SKULL_TIER_7),
    ABICASES(false, ItemType.ACTUALLY_BLUE_ABICASE, ItemType.BLUE_BUT_GREEN_ABICASE, ItemType.BLUE_BUT_RED_ABICASE, ItemType.BLUE_BUT_YELLOW_ABICASE, ItemType.LIGHTER_BLUE_ABICASE, ItemType.REZAR_ABICASE, ItemType.SUMSUNG_G3_ABICASE, ItemType.SUMSUNG_GG_ABICASE),
    CAMPFIRE(true, ItemType.CAMPFIRE_TALISMAN_1, ItemType.CAMPFIRE_TALISMAN_2, ItemType.CAMPFIRE_TALISMAN_3, ItemType.CAMPFIRE_TALISMAN_4, ItemType.CAMPFIRE_TALISMAN_5, ItemType.CAMPFIRE_TALISMAN_6, ItemType.CAMPFIRE_TALISMAN_7, ItemType.CAMPFIRE_TALISMAN_8, ItemType.CAMPFIRE_TALISMAN_9, ItemType.CAMPFIRE_TALISMAN_10, ItemType.CAMPFIRE_TALISMAN_11, ItemType.CAMPFIRE_TALISMAN_12, ItemType.CAMPFIRE_TALISMAN_13, ItemType.CAMPFIRE_TALISMAN_14, ItemType.CAMPFIRE_TALISMAN_15, ItemType.CAMPFIRE_TALISMAN_16, ItemType.CAMPFIRE_TALISMAN_17, ItemType.CAMPFIRE_TALISMAN_18, ItemType.CAMPFIRE_TALISMAN_19, ItemType.CAMPFIRE_TALISMAN_20, ItemType.CAMPFIRE_TALISMAN_21, ItemType.CAMPFIRE_TALISMAN_22, ItemType.CAMPFIRE_TALISMAN_23, ItemType.CAMPFIRE_TALISMAN_24, ItemType.CAMPFIRE_TALISMAN_25, ItemType.CAMPFIRE_TALISMAN_26, ItemType.CAMPFIRE_TALISMAN_27, ItemType.CAMPFIRE_TALISMAN_28, ItemType.CAMPFIRE_TALISMAN_29),
    SOUL_CAMPFIRE(true, ItemType.SOUL_CAMPFIRE_TALISMAN_1, ItemType.SOUL_CAMPFIRE_TALISMAN_2, ItemType.SOUL_CAMPFIRE_TALISMAN_3, ItemType.SOUL_CAMPFIRE_TALISMAN_4, ItemType.SOUL_CAMPFIRE_TALISMAN_5, ItemType.SOUL_CAMPFIRE_TALISMAN_6, ItemType.SOUL_CAMPFIRE_TALISMAN_7, ItemType.SOUL_CAMPFIRE_TALISMAN_8, ItemType.SOUL_CAMPFIRE_TALISMAN_9, ItemType.SOUL_CAMPFIRE_TALISMAN_10, ItemType.SOUL_CAMPFIRE_TALISMAN_11, ItemType.SOUL_CAMPFIRE_TALISMAN_12, ItemType.SOUL_CAMPFIRE_TALISMAN_13, ItemType.SOUL_CAMPFIRE_TALISMAN_14, ItemType.SOUL_CAMPFIRE_TALISMAN_15, ItemType.SOUL_CAMPFIRE_TALISMAN_16, ItemType.SOUL_CAMPFIRE_TALISMAN_17, ItemType.SOUL_CAMPFIRE_TALISMAN_18, ItemType.SOUL_CAMPFIRE_TALISMAN_19, ItemType.SOUL_CAMPFIRE_TALISMAN_20, ItemType.SOUL_CAMPFIRE_TALISMAN_21, ItemType.SOUL_CAMPFIRE_TALISMAN_22, ItemType.SOUL_CAMPFIRE_TALISMAN_23, ItemType.SOUL_CAMPFIRE_TALISMAN_24, ItemType.SOUL_CAMPFIRE_TALISMAN_25, ItemType.SOUL_CAMPFIRE_TALISMAN_26, ItemType.SOUL_CAMPFIRE_TALISMAN_27, ItemType.SOUL_CAMPFIRE_TALISMAN_28, ItemType.SOUL_CAMPFIRE_TALISMAN_29),
    ;

    private final boolean tiered;
    private final ItemType[] talismans;

    TieredTalismansRegistry(boolean tiered, ItemType... talismans) {
        this.tiered = tiered; // true if the next talisman should have higher priority than the one before
        this.talismans = talismans;
    }

    public static int getTier(ItemType talisman) {
        for (TieredTalismansRegistry tieredTalisman : TieredTalismansRegistry.values()) {
            for (int i = 0; i < tieredTalisman.talismans.length; i++) {
                if (tieredTalisman.talismans[i] == talisman) {
                    return tieredTalisman.isTiered() ? i : 0;
                }
            }
        }
        return -1;
    }

    public static TieredTalismansRegistry getTieredTalisman(ItemType talisman) {
        for (TieredTalismansRegistry tieredTalisman : TieredTalismansRegistry.values()) {
            for (ItemType item : tieredTalisman.talismans) {
                if (item == talisman) {
                    return tieredTalisman;
                }
            }
        }
        return null;
    }
}