# The host name or IP address to bind the server to
host-name: 0.0.0.0
# The MongoDB connection URI
mongodb: mongodb://localhost
# The Redis connection URI
redis-uri: redis://localhost:6379
# The secret key used to authenticate with Velocity proxy
velocity-secret: ixmSUgWOgvs7
# Whether to require player authentication on initial connection
require-auth: false
# Whether to enable sandbox features (such as editing items)
sandbox: false
# Integrations with services
integrations:
    # Whether to enable Spark for performance monitoring
    spark: false
    # Whether to enable anti-cheat measures
    anticheat: false
    # Whether to enable ViaVersion for supporting multiple Minecraft versions. This may cause issues of any kind
    via-version: true
    # The DSN to use for Sentry error tracking. If empty, Sentry will be disabled
    sentry-dsn: ''
# Settings related to configuration of Limbo server connections
limbo:
    host-name: 127.0.0.1
    port: 65535
# Resource pack settings keyed by pack name (e.g. testingpack, bedwarspack)
resource-packs: { }
