host-name: 0.0.0.0
transfer-timeout: 800
mongodb: mongodb://hypixel_mongo
redis-url: redis://hypixel_redis:6379
velocity-secret: ixmSUgWOgvs7
require-auth: false
sandbox: false
spark: false
anticheat: false
redis-uri: redis://hypixel_redis:6379
limbo:
    host-name: pico_limbo
    port: 65535
